// Auto-generated by prepare-images.js
export type ImageGroup = {
  mobile: string[];
  desktop: string[];
};
export const heros: ImageGroup = {
  "mobile": [
    "heroMobile.jpg"
  ],
  "desktop": [
    "heroDesktop.jpg"
  ]
};
