// Auto-generated by prepare-images.js
export const images = {
  "Bagni": {
    "mobile": [
      "Bagni/Mobile/Bagno1.jpg",
      "Bagni/Mobile/Bagno10.jpg",
      "Bagni/Mobile/Bagno11.jpg",
      "Bagni/Mobile/Bagno12.jpg",
      "Bagni/Mobile/Bagno14.jpg",
      "Bagni/Mobile/Bagno2.jpg",
      "Bagni/Mobile/Bagno4.jpg",
      "Bagni/Mobile/Bagno5.jpg",
      "Bagni/Mobile/Bagno8.jpg",
      "Bagni/Mobile/Bagno9.jpg"
    ],
    "desktop": [
      "Bagni/Desktop/Bagno6.jpg",
      "Bagni/Desktop/Bagno7.jpg"
    ]
  },
  "Cucine": {
    "mobile": [
      "Cucine/Mobile/Cucina1.jpg",
      "Cucine/Mobile/Cucina2.jpg",
      "Cucine/Mobile/Cucina3.jpg",
      "Cucine/Mobile/Cucina7.jpg",
      "Cucine/Mobile/Cucina8.jpg",
      "Cucine/Mobile/Cucina9.jpg"
    ],
    "desktop": [
      "Cucine/Desktop/Cucina10.jpg",
      "Cucine/Desktop/Cucina4.jpg",
      "Cucine/Desktop/Cucina6.jpg"
    ]
  },
  "Impianti": {
    "mobile": [
      "Impianti/Mobile/Impianti11.jpg",
      "Impianti/Mobile/Impianti2.jpg",
      "Impianti/Mobile/Impianti4.jpg",
      "Impianti/Mobile/Impianti6.jpg",
      "Impianti/Mobile/Impianti7.jpg",
      "Impianti/Mobile/Impianti8.jpg",
      "Impianti/Mobile/Impianti9.jpg"
    ],
    "desktop": [
      "Impianti/Desktop/Impianti1.jpg",
      "Impianti/Desktop/Impianti3.jpg",
      "Impianti/Desktop/Impianti5.jpg"
    ]
  },
  "Pavimenti": {
    "mobile": [
      "Pavimenti/Mobile/Pavimenti1.jpg",
      "Pavimenti/Mobile/Pavimenti10.jpg",
      "Pavimenti/Mobile/Pavimenti2.jpg",
      "Pavimenti/Mobile/Pavimenti3.jpg",
      "Pavimenti/Mobile/Pavimenti4.jpg",
      "Pavimenti/Mobile/Pavimenti5.jpg",
      "Pavimenti/Mobile/Pavimenti6.jpg",
      "Pavimenti/Mobile/Pavimenti8.jpg"
    ],
    "desktop": [
      "Pavimenti/Desktop/Pavimenti11.jpg",
      "Pavimenti/Desktop/Pavimenti4.jpg",
      "Pavimenti/Desktop/Pavimenti9.jpg"
    ]
  },
  "Ristrutturazioni": {
    "mobile": [
      "Ristrutturazioni/Mobile/Ristrutturazioni1.jpg",
      "Ristrutturazioni/Mobile/Ristrutturazioni10.jpg",
      "Ristrutturazioni/Mobile/Ristrutturazioni11.jpg",
      "Ristrutturazioni/Mobile/Ristrutturazioni2.jpg",
      "Ristrutturazioni/Mobile/Ristrutturazioni3.jpg",
      "Ristrutturazioni/Mobile/Ristrutturazioni4.jpg",
      "Ristrutturazioni/Mobile/Ristrutturazioni9.jpg"
    ],
    "desktop": [
      "Ristrutturazioni/Desktop/Ristrutturazioni1.jpg",
      "Ristrutturazioni/Desktop/Ristrutturazioni5.jpg",
      "Ristrutturazioni/Desktop/Ristrutturazioni7.jpg",
      "Ristrutturazioni/Desktop/Ristrutturazioni8.jpg"
    ]
  },
  "Salotti": {
    "mobile": [
      "Salotti/Mobile/Salotto2.jpg",
      "Salotti/Mobile/Salotto3.jpg",
      "Salotti/Mobile/Salotto4.jpg",
      "Salotti/Mobile/Salotto8.jpg",
      "Salotti/Mobile/Salotto9.jpg"
    ],
    "desktop": [
      "Salotti/Desktop/Salotto1.jpg",
      "Salotti/Desktop/Salotto5.jpg"
    ]
  }
};
